// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOrStikuy4D9IUVL4-6dqvULFL1N0L-aw',
    appId: '1:226155379212:web:b6e0162402e69579ea4c29',
    messagingSenderId: '226155379212',
    projectId: 'saiflash-flutter-app',
    authDomain: 'saiflash-flutter-app.firebaseapp.com',
    storageBucket: 'saiflash-flutter-app.appspot.com',
    measurementId: 'G-LJKRVZJP1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBX9lwpU0wd8dVYf9w38Ln_hRFW9XRfW4',
    appId: '1:1077065175764:android:6d1b217ad86640af366141',
    messagingSenderId: '1077065175764',
    projectId: 'flutter-saiflash-quiz-app',
    storageBucket: 'flutter-saiflash-quiz-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY14IvThaRbN6mU7WG58SR7ez7DTBJXW8',
    appId: '1:1077065175764:ios:13db0adc95c52041366141',
    messagingSenderId: '1077065175764',
    projectId: 'flutter-saiflash-quiz-app',
    storageBucket: 'flutter-saiflash-quiz-app.appspot.com',
    iosBundleId: 'com.example.saiflash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjX7TA3zDQOYns0kJLGjcremwshZTBdFQ',
    appId: '1:226155379212:ios:82bc77333acd90a0ea4c29',
    messagingSenderId: '226155379212',
    projectId: 'saiflash-flutter-app',
    storageBucket: 'saiflash-flutter-app.appspot.com',
    iosBundleId: 'com.example.saiflash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOrStikuy4D9IUVL4-6dqvULFL1N0L-aw',
    appId: '1:226155379212:web:bf20f66d64e53d9cea4c29',
    messagingSenderId: '226155379212',
    projectId: 'saiflash-flutter-app',
    authDomain: 'saiflash-flutter-app.firebaseapp.com',
    storageBucket: 'saiflash-flutter-app.appspot.com',
    measurementId: 'G-5TX233XG7F',
  );
}